name: 测试解密jsm.txt

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-dec:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4
        with:
          path: main_repo

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装 tvbox.py 依赖
        run: |
          python -m pip install --upgrade pip
          pip install pycryptodome

      - name: 解密 jsm.txt 为 jsm.bin
        run: |
          cd main_repo
          python tvbox.py https://9877.kstore.space/one.json xs.json dec
          if [ -f "jsm.txt" ]; then
            python tools/tvbox.py jsm.txt jsm.bin dec
          else
            echo "未找到 jsm.txt，跳过解密"
          fi

      - name: 提交并推送解密后的文件到仓库
        run: |
          cd main_repo
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add jsm.bin
          git diff --staged --quiet || git commit -m "auto: 已完成 jsm.txt 解密"
          git push
